<a href="https://colab.research.google.com/github/ntxucb/W2-Introduccion-Data-Science/blob/main/D1_Analisis_de_Datos_Python_NTXUCB_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Workshop - Análisis de Datos con Python - NeuroTechUCB

## ¿Necesito el Análisis de Datos?

<img src="https://miro.medium.com/max/565/1*x49QbCxxTYScuV728oBelw.jpeg" width="400">
<br>
<img src="https://i.ibb.co/JkfqHqk/nma.jpg" alt="nma" border="0" width="400">
<br>
<img src="https://i.redd.it/nc5ua4x8lfg31.png" width="400">
<br>
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSytVPieZUKXxHDkSVudwmW8NNAVy5yo7e2Ng&usqp=CAU" width="400">

## ¿Por qué Python?

<img src="https://miro.medium.com/max/1200/0*GZWyB9r_3sZPFjly.png" width="400">
<br>

<img src="https://miro.medium.com/max/1400/1*PMvSWYzafqUVMsmQDsWEPA.png" width="400">

## ¿Qué es una libreria?

Una librería, en programación, es una colección de código previamente escrito (usualmente expuesto como funciones y objetos) que nos ayudan a realizar tareas "comunes" o "tradicionales" de forma rápida y optimizada.

## ¿Qué es una función?

Una función en programación es similar al concepto que se maneja en cualquier otra rama del conocimiento se puede modelar como una máquina que transforma ciertas entradas en ciertas salidas.

<img src="https://s3-us-west-2.amazonaws.com/courses-images/wp-content/uploads/sites/1861/2017/06/23161835/apple-slicing-function.png" width="500" >

Una función en Pyhton se ve de la siguiente manera:

<img src="https://i.ibb.co/nfQpPbX/functions.png" width="500">

In [ ]:
# Definicion de la funcion
def sumar_dos_numeros(a, b):
  suma = a + b
  return suma

In [ ]:
# Llamada a la funcion
num1 = 45
num2 = 12
sumar_dos_numeros(num1, num2)

57

## Libreria NumPy

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1200px-NumPy_logo_2020.svg.png" height="100">

NumPy es el nombre corto para **Numerical Python** y es una libreria que nos ayuda a manejar **arreglos multidimensionales** de datos.

Esta libreria es importante para el Análisis de Datos debido a que muchos datasets (sobre todo de señales de EEG o MEG) pueden ser transformados a arreglos multidimensionales. Además que las librerias que se verán en las próximas sesiones estan basadas en NumPy.

In [ ]:
# Importamos la libreria
import numpy as np

mi_arreglo = np.arange(1,50,2) # arreglo con los numeros del 1 al 50 saltando de 2 en 2
mi_arreglo

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [ ]:
# Las listas de Python no son lo mismo que los ARREGLOS de NumPy
mi_lista = list(range(1,50,2))
mi_lista

[1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49]

In [ ]:
print("El tipo de dato del arreglo de numpy es",type(mi_arreglo))
print("El tipo de dato de la lista es",type(mi_lista))

El tipo de dato del arreglo de numpy es <class 'numpy.ndarray'>
El tipo de dato de la lista es <class 'list'>


In [ ]:
# Por ejemplo
mi_arreglo+10

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49, 51, 53, 55, 57, 59])

In [ ]:
# Operaciones con numpy
arreglo1 = mi_arreglo + 10
arreglo2 = mi_arreglo * 5
arreglo3 = arreglo1 + arreglo2
arreglo3

array([ 16,  28,  40,  52,  64,  76,  88, 100, 112, 124, 136, 148, 160,
       172, 184, 196, 208, 220, 232, 244, 256, 268, 280, 292, 304])

In [ ]:
# Puede comparar elemento con elemento
arreglo1 > arreglo2

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [ ]:
# Obtener el minimo de un arreglo
mi_arreglo.min()

1

In [ ]:
# Obtener el maximo de un arreglo
mi_arreglo.max()

49

In [ ]:
# Obtener el promedio
mi_arreglo.mean()

25.0

In [ ]:
# Obtener la suma del arreglo
mi_arreglo.sum()

625

In [ ]:
arr = np.random.randint(1,20,15)
arr

array([12,  4, 18, 14,  9,  8, 16, 18, 19, 12,  7, 15,  1, 17,  8])

In [ ]:
# Ordenar el arreglo
arr.sort()
arr

array([ 1,  4,  7,  8,  8,  9, 12, 12, 14, 15, 16, 17, 18, 18, 19])

## Arreglos Multidimensionales

Los arreglos multidimensionales no son mas que *arreglos de arreglos* y pueden tener las formas que tienen en la imagen.

<img src="https://i.ibb.co/bmQp4xQ/arrays.png" height="300">

In [ ]:
# Arreglo 1D
arreglo_1d = np.array([7,2,9,10])
arreglo_1d

array([ 7,  2,  9, 10])

In [ ]:
# Arreglo 2D
arreglo_2d = np.array([ [5.2,3.0,4.5] , [9.1,0.1,0.3] ])
arreglo_2d

array([[5.2, 3. , 4.5],
       [9.1, 0.1, 0.3]])

In [ ]:
print(arreglo_1d.shape)
print(arreglo_2d.shape)

(4,)
(2, 3)


In [ ]:
# Crear un arreglo solo con unos
unos = np.ones(5)
unos

array([1., 1., 1., 1., 1.])

In [ ]:
# Crear un arreglo solo de ceros
ceros = np.zeros((5,7))
ceros

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# Crear un arreglo de numeros aleatorios
aleatorios = np.random.rand(2,5,4)
aleatorios

array([[[0.94738551, 0.17982155, 0.47132842, 0.41493558],
        [0.85324683, 0.53589251, 0.83345666, 0.73194881],
        [0.51638099, 0.86693345, 0.37678835, 0.3465138 ],
        [0.17015358, 0.2716704 , 0.38801232, 0.62647602],
        [0.50047892, 0.83991267, 0.35252829, 0.24536343]],

       [[0.40107431, 0.38735255, 0.28737797, 0.36958216],
        [0.56220128, 0.32456132, 0.94342214, 0.26225715],
        [0.73567617, 0.48741345, 0.06070371, 0.69109385],
        [0.43245541, 0.67063941, 0.70794792, 0.63257607],
        [0.07649292, 0.26516573, 0.14791464, 0.00650775]]])

### Ejercicio 1
Como crearias un arreglo de numpy con los numeros del 5 al 12


## Reshape de un arreglo de numpy (np.reshape)

[Referencia a la documentación](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

Hacer un reshape de un arreglo de numpy es cambiar el shape de un arreglo es decir podemos "reordenar" los arreglos de numpy aumentando sus dimensiones o reduciendolas.

In [ ]:
# Cambiando un arreglo de 3 dimensiones a un arreglo 2D
arreglo_3d = np.random.rand(4,3,2)
arreglo_2d = np.reshape(arreglo_3d, (12,2))
print('Arreglo 3D')
print(arreglo_3d)
print('Arreglo 2D')
print(arreglo_2d)

Arreglo 3D
[[[0.45495087 0.62690813]
  [0.82461421 0.06986207]
  [0.661009   0.51242156]]

 [[0.87972016 0.69895597]
  [0.69327542 0.17557998]
  [0.5675243  0.4868568 ]]

 [[0.96986159 0.26686396]
  [0.84847731 0.45324728]
  [0.85054928 0.34722659]]

 [[0.96976545 0.02373614]
  [0.81119499 0.37532195]
  [0.20318604 0.48917439]]]
Arreglo 2D
[[0.45495087 0.62690813]
 [0.82461421 0.06986207]
 [0.661009   0.51242156]
 [0.87972016 0.69895597]
 [0.69327542 0.17557998]
 [0.5675243  0.4868568 ]
 [0.96986159 0.26686396]
 [0.84847731 0.45324728]
 [0.85054928 0.34722659]
 [0.96976545 0.02373614]
 [0.81119499 0.37532195]
 [0.20318604 0.48917439]]


In [ ]:
# Cambiando un arreglo 1D a un arreglo 3D
arreglo_1d = np.random.rand(18)
arreglo_3d = np.reshape(arreglo_1d, (3,3,2))
print('Arreglo 1D')
print(arreglo_1d)
print('Arreglo 3D')
print(arreglo_3d)

Arreglo 1D
[0.87104947 0.23747786 0.1466366  0.7051252  0.32007247 0.77685004
 0.93532559 0.05797861 0.27585275 0.88752243 0.58262733 0.20546383
 0.88883089 0.61643078 0.29969332 0.01692815 0.13287768 0.00159403]
Arreglo 3D
[[[0.87104947 0.23747786]
  [0.1466366  0.7051252 ]
  [0.32007247 0.77685004]]

 [[0.93532559 0.05797861]
  [0.27585275 0.88752243]
  [0.58262733 0.20546383]]

 [[0.88883089 0.61643078]
  [0.29969332 0.01692815]
  [0.13287768 0.00159403]]]


### Ejercicio 2
Realiza un código para producir un arreglo de numpy con el siguiente contenido:

<img src="https://i.ibb.co/w7YkyZY/matrix1.png" width="300">

## Indices y Slicing en Arreglos

Al igual que en las listas los arreglos siguen la misma convención de indices y posiciones, sin embargo ahora en una posición se puede tener otro arreglo, como se muestra en los siguientes ejemplos.

In [ ]:
# Obtendremos la posicion 0, que es un arreglo de tamaño 2,5
aleatorios = np.random.rand(2,5)
aleatorios

array([[0.64617727, 0.27142722, 0.85888689, 0.36125634, 0.10556385],
       [0.70014658, 0.64980645, 0.47332203, 0.22934902, 0.51418523]])

In [ ]:
aleatorios[0]

array([0.64617727, 0.27142722, 0.85888689, 0.36125634, 0.10556385])

In [ ]:
aleatorios[0][3]

0.36125633866585016

In [ ]:
numeros = np.arange(0,28,2)
numeros

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26])

In [ ]:
# Slice de un arreglo unidimensional [inicio:final:paso]
numeros[4:10:2]

array([ 8, 12, 16])

In [ ]:
# Slice de un arreglo multidimensional
aleatorios = np.random.rand(3,4,5)
print('Arreglo Original')
print(aleatorios)
# Slice multidimensional
print('Slice')
slice_aleatorios = aleatorios[1, 0:2, 1:3]
print(slice_aleatorios)

Arreglo Original
[[[0.23860882 0.0200997  0.35854385 0.89481405 0.02878954]
  [0.61878118 0.44280347 0.18454364 0.28203873 0.16693602]
  [0.37690536 0.80720222 0.81246327 0.70810192 0.3392793 ]
  [0.26025466 0.52848924 0.22356965 0.99852401 0.44677931]]

 [[0.18220202 0.53366042 0.87548025 0.58780079 0.02702968]
  [0.76863632 0.87863997 0.88483675 0.61201961 0.43732547]
  [0.80122014 0.18581021 0.97629654 0.10169817 0.90597394]
  [0.19386185 0.6597007  0.26902343 0.5972404  0.45947224]]

 [[0.16463461 0.20690883 0.1818535  0.37992897 0.76202402]
  [0.69256165 0.2210195  0.94013235 0.1891494  0.64036563]
  [0.22073719 0.20372537 0.52591358 0.10321855 0.41548155]
  [0.27025645 0.88343166 0.56234509 0.79165788 0.43723478]]]
Slice
[[0.53366042 0.87548025]
 [0.87863997 0.88483675]]


### Ejercicio 3

En base al arreglo de numpy **aleatorios** proponer un slice que obtenga el siguiente arreglo

```
array([[0.8990746 , 0.47966254, 0.02385993],
       [0.42318332, 0.17149375, 0.60733069]])
```




## Concatenar arreglos de numpy (np.concatenate)

[Referencia a la documentación](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html)

Es posible "pegar" dos o más arreglos, por alguno de sus indices.

In [ ]:
# Concatenar arreglos unidimensionales puede generar un arreglo unidimensional
arreglo1 = np.array([1,2,3,4,5,6])
arreglo2 = arreglo1 * 2
arreglo3 = arreglo1 + 10

arreglo_final = np.concatenate([arreglo1, arreglo2, arreglo3])
arreglo_final

array([ 1,  2,  3,  4,  5,  6,  2,  4,  6,  8, 10, 12, 11, 12, 13, 14, 15,
       16])

In [ ]:
# Pero tambien puede generar arreglos de 2 dimensiones
arreglo1 = arreglo1.reshape(2,3)
arreglo2 = arreglo2.reshape(2,3)
arreglo3 = arreglo3.reshape(2,3)
arreglo_final = np.concatenate([arreglo1, arreglo2, arreglo3],axis=1)
arreglo_final

array([[ 1,  2,  3,  2,  4,  6, 11, 12, 13],
       [ 4,  5,  6,  8, 10, 12, 14, 15, 16]])

### Ejercicio 4

Realiza un código para producir un arreglo de numpy con el siguiente contenido:

<img src="https://i.ibb.co/wMhgr7j/matrix2.png" width="300">

## ¿Quiero aprender más?
<img src="https://images-na.ssl-images-amazon.com/images/I/515XdK-YtFL._SX379_BO1,204,203,200_.jpg" width="300">